import express from "express";
const router = express.Router();
import catRouter from "./category/cat.routes.js";
import userRouter from "./User/user.routes.js";
import advertisementRouter from "./Advertisement/advertisement.routes.js";
import storeRouter from "./store/store.routes.js";
import postRouter from "./Posts/posts.routes.js";
import postCategoryRouter from "./PostCategory/postCategory.routes.js";
import ReviewRouter from "./review/review.routes.js";
router.use("/test", () => {});

router.use("/category", catRouter);
router.use("/store", storeRouter);
router.use("/postCategory", postCategoryRouter);
router.use("/advertisement", advertisementRouter);
router.use("/post", postRouter);
router.use("/user", userRouter);
router.use("/review", ReviewRouter);
router.use("/advertisement", advertisementRouter);
export default router;
